### ISSUE TITLE
docker cannot use "tlsverify" when docker build

### ISSUE THREAD

**Issue by bobcai** [regis-leray/sbt-docker#14]
my docker environment needs tls, but i found that in plugin code, it is not supported. can this be improve?
Thanks.

**Comment by regis-leray** [comment]
yes of course, i didnt see your message.

I just noticed we are missing a way to provide some docker args like 

```bash
docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem \
  -H=$HOST:2376 version
```

i will add another extra argument to provide more flexibility

```scala
lazy val root = project.in(file("."))
  .settings(
    dockerArgs = Seq("--tlsverify")
)
```
